<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="jetbot">

  <!-- Premenné -->
  <xacro:property name="wheel_radius" value="0.033"/>
  <xacro:property name="wheel_length" value="0.02"/>
  <xacro:property name="body_radius" value="0.1066"/>
  <xacro:property name="body_length" value="0.05"/>
  <xacro:property name="caster_radius" value="0.015"/>
  <xacro:property name="camera_size" value="0.03"/>
  <xacro:property name="lidar_radius" value="0.04"/>
  <xacro:property name="lidar_length" value="0.02"/>
  <xacro:property name="lidar_base_radius" value="0.04"/>
  <xacro:property name="lidar_base_length" value="0.035"/>

  <!-- Materiály -->
  <material name="green"><color rgba="0 1 0 1"/></material>
  <material name="blue"><color rgba="0 0 1 1"/></material>
  <material name="black"><color rgba="0 0 0 1"/></material>

  <!-- Telo robota -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${body_radius}" length="${body_length}"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${body_radius}" length="${body_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.5"/>
      <inertia ixx="0.02" ixy="0" ixz="0" iyy="0.02" iyz="0" izz="0.04"/>
    </inertial>
    <!-- Sensor pre IMU -->
    <sensor type="imu" name="imu_sensor">
      <update_rate>100</update_rate>
      <always_on>1</always_on>
      <visualize>true</visualize>
      <topic>/imu</topic>
    </sensor>
    <!-- Sensor pre kontaktný senzor -->
    <sensor type="contact" name="contact_sensor">
      <update_rate>100</update_rate>
      <contact>
        <collision>base_link_collision</collision>
        <collision>left_wheel_collision</collision>
        <collision>right_wheel_collision</collision>
      </contact>
    </sensor>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Green</material>
    <mu1>0.5</mu1>
    <mu2>0.5</mu2>
  </gazebo>

  <!-- Makro pre koleso -->
  <xacro:macro name="wheel" params="name x y z">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5707 0 0"/>
        <material name="blue"/>
      </visual>
      <collision name="${name}_collision">
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5707 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.002"/>
      </inertial>
    </link>
    <gazebo reference="${name}">
      <material>Gazebo/Blue</material>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
    </gazebo>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Vytvorenie hlavných kolies -->
  <xacro:wheel name="left_wheel" x="0" y="0.1066" z="-0.02"/>
  <xacro:wheel name="right_wheel" x="0" y="-0.1066" z="-0.02"/>

  <!-- Makro pre pomocné koleso -->
  <xacro:macro name="caster_wheel" params="name x">
    <link name="${name}">
      <visual>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005"/>
      </inertial>
    </link>
    <gazebo reference="${name}">
      <material>Gazebo/Black</material>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
    </gazebo>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} 0 -0.027" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-0.1" upper="0.1" effort="0.1" velocity="1.0"/>
      <dynamics damping="0.1" friction="0.05"/>
    </joint>
  </xacro:macro>

  <!-- Vytvorenie pomocných kolies -->
  <xacro:caster_wheel name="balance_wheel" x="0.09"/>
  <xacro:caster_wheel name="balance_wheel_2" x="-0.09"/>

  <!-- Kamera -->
  <link name="camera">
    <visual>
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>
  <gazebo reference="camera">
    <material>Gazebo/Black</material>
    <sensor type="camera" name="sim_camera">
      <update_rate>30</update_rate>
      <camera>
        <horizontal_fov>1.39626</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
      </camera>
      <plugin name="gz::sim::systems::Camera" filename="gz-sim-camera-system">
        <topic>/image_raw</topic>
        <frame_id>camera</frame_id>
      </plugin>
    </sensor>
  </gazebo>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera"/>
    <origin xyz="0.1 0 0.03" rpy="0 0 0"/>
  </joint>

  <!-- Podstavec pre LIDAR -->
  <link name="lidar_base">
    <visual>
      <geometry>
        <cylinder radius="${lidar_base_radius}" length="${lidar_base_length}"/>
      </geometry>
      <origin xyz="0 0 ${lidar_base_length / 2}" rpy="0 0 0"/>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_base_radius}" length="${lidar_base_length}"/>
      </geometry>
      <origin xyz="0 0 ${lidar_base_length / 2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 ${lidar_base_length / 2}"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.002"/>
    </inertial>
  </link>
  <gazebo reference="lidar_base">
    <material>Gazebo/Green</material>
  </gazebo>
  <joint name="lidar_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_base"/>
    <origin xyz="0 0 0.025" rpy="0 0 0"/>
  </joint>

  <!-- LIDAR -->
  <link name="lidar">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>
  <gazebo reference="lidar">
    <material>Gazebo/Black</material>
    <sensor type="gpu_lidar" name="lidar_sensor">
      <update_rate>20</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.57</min_angle>
            <max_angle>1.57</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.12</min>
          <max>10.0</max>
        </range>
      </ray>
      <plugin name="gz::sim::systems::GpuLidar" filename="gz-sim-gpu-lidar-system">
        <topic>/scan</topic>
        <frame_id>lidar</frame_id>
      </plugin>
    </sensor>
  </gazebo>
  <joint name="lidar_joint" type="fixed">
    <parent link="lidar_base"/>
    <child link="lidar"/>
    <origin xyz="0 0 0.035" rpy="0 0 0"/>
  </joint>

  <!-- Diferenciálny pohon -->
  <gazebo>
    <plugin name="gz::sim::systems::DiffDrive" filename="gz-sim-diff-drive-system">
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>0.21325</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_topic>odom</odom_topic>
      <odom_publish_frequency>10</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <cmd_timeout>0.5</cmd_timeout>
      <tf_topic>tf</tf_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
      <publish_tf>true</publish_tf>
    </plugin>
  </gazebo>

  <!-- JointStatePublisher plugin -->
  <gazebo>
    <plugin name="gz::sim::systems::JointStatePublisher" filename="gz-sim-joint-state-publisher-system">
      <topic>joint_states</topic>
    </plugin>
  </gazebo>

</robot>
