---
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

gz_ros2_control:
  ros__parameters:
    robot_description: "robot_description"
    hardware_type: "gz_ros2_control/GazeboSimSystem"
    joints:
      - left_wheel_joint
      - right_wheel_joint

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.22
    wheel_radius: 0.03
    use_stamped_vel: false
    cmd_vel_topic: "/model/jetbot/cmd_vel"
    odometry_topic: "/jetbot/odom"
    odometry_frame_id: "odom"
    robot_base_frame_id: "base_link"
    transform_broadcast_odom: true
    publish_rate: 50.0
